base_image:
  - android-base.Dockerfile
  - publish-base-image.sh
sdk_images:
  - android-sdk.Dockerfile
  - publish-sdk-image.sh
emulator_images:
  - android-emulator.Dockerfile
  - publish-emulator-image.sh
emulator_v2_images:
  - android-emulator-v2.Dockerfile
  - publish-emulator-v2-image.sh