base_image:
  - android-base.Dockerfile
  - publish-base-image.sh
sdk_images:
  - android-30.Dockerfile
  - publish-sdk-image.sh
emulator_images:
  - android-emulator-30.Dockerfile
  - publish-emulator-image.sh