base_image:
  - android-base.Dockerfile
  - publish-base-image.sh
sdk_images:
  - android-sdk.Dockerfile
  - publish-sdk-image.sh
emulator_images:
  - android-emulator.Dockerfile
  - publish-emulator-image.sh