name: Release image

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        if: github.event_name == 'push'
        id: changes
        with:
          filters: '.github/filters-emulator.yml'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ steps.changes.outputs.emulator-image == 'true' }}
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and publish emulator-33.Dockerfile
        if: ${{ steps.changes.outputs.emulator-image == 'true' }}
        run: sh publish-emulator-33-image.sh
