name: Build and Publish Images

on:
  push:
    branches:
      - main

jobs:
  publish-base-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        if: github.event_name == 'push'
        id: changes
        with:
          filters: '.github/filters.yml'
      - name: Login to Docker Hub
        if: ${{ github.event_name == 'schedule' || steps.changes.outputs.base_image == 'true' || steps.changes.outputs.sdk_images == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and publish android-base.Dockerfile
        if: ${{ github.event_name == 'schedule' || steps.changes.outputs.base_image == 'true' }}
        run: sh publish-base-image.sh

  publish-sdk-image:
    needs: publish-base-image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 30, 33 ]

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        if: github.event_name == 'push'
        id: changes
        with:
          filters: '.github/filters.yml'
      - name: Login to Docker Hub
        if: ${{ github.event_name == 'schedule' || steps.changes.outputs.base_image == 'true' || steps.changes.outputs.sdk_images == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and publish android-sdk-30.Dockerfile
        if: ${{ github.event_name == 'schedule' || steps.changes.outputs.base_image == 'true' || steps.changes.outputs.sdk_images == 'true' }}
        run: sh publish-sdk-image.sh ${{ matrix.api-level }}

  publish-emulator-image:
    needs: publish-sdk-image
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 30, 33 ]

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        if: github.event_name == 'push'
        id: changes
        with:
          filters: '.github/filters.yml'
      - name: Login to Docker Hub
        if: ${{ github.event_name == 'schedule' || steps.changes.outputs.base_image == 'true' || steps.changes.outputs.sdk_images == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and publish android-emulator-30.Dockerfile
        if: ${{ github.event_name == 'schedule' || steps.changes.outputs.base_image == 'true' || steps.changes.outputs.sdk_images == 'true' || steps.changes.outputs.emulator_images == 'true' }}
        run: sh publish-emulator-image.sh ${{ matrix.api-level }}

  publish-emulator-v2-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 33 ]

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        if: github.event_name == 'push'
        id: changes
        with:
          filters: '.github/filters.yml'
      - name: Login to Docker Hub
        if: ${{ github.event_name == 'schedule' || steps.changes.outputs.base_image == 'true' || steps.changes.outputs.sdk_images == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and publish android-emulator-v2.Dockerfile
        if: ${{ github.event_name == 'schedule' || steps.changes.outputs.emulator_v2_images == 'true' }}
        run: sh publish-emulator-v2-image.sh ${{ matrix.api-level }}