name: Build image

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker image api-34
        uses: docker/build-push-action@v4
        with:
          push: true
          file: ${{ matrix.gpu.file }}
          tags: nilsjrfn/docker-android:api-34
          build-args: |
            API_LEVEL=34
            IMG_TYPE=google_apis
