name: Build image

on:
  push:
    branches:
      - main

jobs:
  publish-android-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 33, 34 ]

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker image api-34
        uses: docker/build-push-action@v5
        with:
          push: true
          file: android-emulator.Dockerfile
          tags: nilsjrfn/docker-android:api-${{ matrix.api-level }}
          build-args: |
            API_LEVEL=${{ matrix.api-level }}
            IMG_TYPE=google_apis

  publish-maestro-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 33, 34 ]

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build Docker image api-34
        uses: docker/build-push-action@v5
        with:
          push: true
          file: android-emulator-maestro.Dockerfile
          tags: nilsjrfn/docker-android:api-${{ matrix.api-level }}-maestro
          build-args: |
            API_LEVEL=${{ matrix.api-level }}
            IMG_TYPE=google_apis
