name: Build image

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ steps.changes.outputs.emulator-image == 'true' }}
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and publish android-emulator.Dockerfile
        if: ${{ steps.changes.outputs.emulator-image == 'true' }}
        run: sh publish-android-emulator-image.sh
